//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneBelote.Strings {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OneBelote.Strings.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I usually play Belote with friends or family, so I decided to develop an application that helps me to count the score of the game, and why not share my app with you ! I wanted to provide a simple, clean and easy-to-use app so people can quickly note their scores..
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutLabel {
            get {
                return ResourceManager.GetString("AboutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Announcement.
        /// </summary>
        internal static string Announcement {
            get {
                return ResourceManager.GetString("Announcement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to save this game ?.
        /// </summary>
        internal static string ConfirmationSave {
            get {
                return ResourceManager.GetString("ConfirmationSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alsatian (French region) in the soul and Windows developer for several years, I enjoy developing Windows 10 applications to provide quality content to the platform, and facilitate the daily lives of people..
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On the left you can access to a menu allowing you to create a new game or watch the last games you saved..
        /// </summary>
        internal static string HomeAppDesc {
            get {
                return ResourceManager.GetString("HomeAppDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BeloteScoring helps you during your belote parties to record the scores and calculate totals..
        /// </summary>
        internal static string HomeDescription {
            get {
                return ResourceManager.GetString("HomeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enjoy !.
        /// </summary>
        internal static string HomeEnjoy {
            get {
                return ResourceManager.GetString("HomeEnjoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t hesitate to report your feedbacks !.
        /// </summary>
        internal static string HomeFeedback {
            get {
                return ResourceManager.GetString("HomeFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string HomeLabel {
            get {
                return ResourceManager.GetString("HomeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other suits.
        /// </summary>
        internal static string HomeOther {
            get {
                return ResourceManager.GetString("HomeOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trump suit.
        /// </summary>
        internal static string HomeTrump {
            get {
                return ResourceManager.GetString("HomeTrump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to my application !.
        /// </summary>
        internal static string HomeWelcome {
            get {
                return ResourceManager.GetString("HomeWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last parties.
        /// </summary>
        internal static string LastParties {
            get {
                return ResourceManager.GetString("LastParties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New game.
        /// </summary>
        internal static string NewGame {
            get {
                return ResourceManager.GetString("NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string NoneContent {
            get {
                return ResourceManager.GetString("NoneContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        internal static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving.
        /// </summary>
        internal static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Them.
        /// </summary>
        internal static string Them {
            get {
                return ResourceManager.GetString("Them", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Them.
        /// </summary>
        internal static string ThemContent {
            get {
                return ResourceManager.GetString("ThemContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why BeloteScoring ?.
        /// </summary>
        internal static string TitleAbout {
            get {
                return ResourceManager.GetString("TitleAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi, my name is Christophe.
        /// </summary>
        internal static string TitleDescription {
            get {
                return ResourceManager.GetString("TitleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Us.
        /// </summary>
        internal static string Us {
            get {
                return ResourceManager.GetString("Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Us.
        /// </summary>
        internal static string UsContent {
            get {
                return ResourceManager.GetString("UsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your score.
        /// </summary>
        internal static string YourScore {
            get {
                return ResourceManager.GetString("YourScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified score is not a number. Please enter a correct value.
        /// </summary>
        internal static string YourScoreError {
            get {
                return ResourceManager.GetString("YourScoreError", resourceCulture);
            }
        }
    }
}
